#ifndef WAFEMEASURETEMPLATE_COLORFOCUS_CONTROL_H
#define WAFEMEASURETEMPLATE_COLORFOCUS_CONTROL_H

#include "../colorFocusContrlDemo/colorFocus_control.h"

#endif // WAFEMEASURETEMPLATE_COLORFOCUS_CONTROL_H
